internal/api/keppel/accounts.go
internal/api/keppel/accounts_test.go
internal/api/keppel/fixtures/delete-account-000.sql
internal/api/keppel/manifests_test.go
internal/api/keppel/peers_test.go
internal/api/keppel/quotas_test.go
internal/api/keppel/repos_test.go

to remove all contents of accounts without triggering foreign key constraints

Delete image lists before manifests in account deletion

---

Makefile.maker.yaml

Merge after https://github.com/sapcc/go-makefile-maker/pull/29 .

renovate: enable for OCI conformance workflow

---

internal/api/registry/replication_test.go
internal/api/registry/shared_test.go
internal/drivers/openstack/keystone.go
internal/tasks/manifests_test.go
internal/test/mock_roundtripper.go
internal/test/setup.go
main.go

My overwriting of DefaultClient.Transport was based on incorrect assumptions about how DefaultClient and DefaultTransport interact. It's always enough to only fiddle with DefaultTransport, since DefaultClient will default to using it anyway (as will freshly-constructed http.Client instances like the one in gophercloud.ProviderClient).

do not patch http.DefaultClient

---

internal/api/registry/manifests_test.go
internal/processor/manifests.go

List manifests do not have an image config, so they cannot have labels themselves. However, it would be nice to show labels on list manifests (i.e. multi-arch images): When a repo contains multi-arch images, the labeled single-arch images are buried in the "Untagged images" section and thus practically no labels appear on the UI.
To make the label display for multi-arch images useful, this PR makes Keppel populate the `labels_json` field of multi-arch images (i.e. list manifests) with all labels that the constituent single-arch images agree on.

populate labels_json for list manifests

---

internal/api/registry/manifests_test.go
internal/tasks/accounts.go
internal/tasks/blob_mounts.go
internal/tasks/blobs.go
internal/tasks/image_gc.go
internal/tasks/janitor.go
internal/tasks/janitor_test.go
internal/tasks/manifests.go
internal/tasks/shared_test.go
internal/tasks/storage.go

This came out of an investigation into our vulnerability check performance. The queue length metric is very jumpy: Sometimes 1000 images become due for a vulnerability check at the same time, and then eventually they are all checked in rapid succession and the queue length drops by 1000 again. That makes the queue length metric not very useful as an overall measurement of how far we're lagging behind in vulnerability checks.
With this change, once a task is completed, we schedule the next task with a certain random variation. For example, a vulnerability check is supposed to be executed hourly. With this change, we're setting the next scheduled check not at exactly 60 minutes from now, but at somewhere between 54-66 minutes from now. This should smoothen out the workload and thus make the …

janitor: add jitter to task schedules

---

go.mod
go.sum
internal/api/registry/manifests.go
internal/api/registry/shared_test.go
internal/client/download.go
internal/keppel/manifest.go
vendor/github.com/timewasted/go-accept-headers/LICENSE
vendor/github.com/timewasted/go-accept-headers/README.md
vendor/github.com/timewasted/go-accept-headers/accept.go
vendor/github.com/timewasted/go-accept-headers/helpers.go
vendor/modules.txt

The special case rules get moved into the ParsedManifest interface. According to gocognit, this reduces the complexity of handleGetOrHeadManifest() from 100 to 66. I also used the opportunity to turn an incorrect 404 response into the more appropriate 406 (Not Acceptable).
A change was needed in the RepoClient since my understanding of the Accept header was actually incorrect. It's not allowed to have multiple Accept headers. Instead, all acceptable MIME types, must be listed in a single header.

refactor Accept handler handling to reduce cognitive complexity

---

cmd/validate/main.go
internal/client/validate.go

We already had a cache for the scope of a single ValidateManifest() and its recursive subcalls, but that was not really helpful. We only stand to gain when reusing the validation results for common base layers shared by multiple images.
```
$ ./build/keppel validate alpine:latest alpine:3.17 --platform-filter '[{"os":"linux","architecture":"amd64"}]'
2023/03/17 16:38:57 INFO: interpreting alpine:latest as docker-pullable://registry-1.docker.io/alpine:latest
2023/03/17 16:39:23 INFO: manifest sha256:ff6bdca1701f3a8a67e328815ff2346b0e4067d32ec36b7992c1fdc001dc8517 looks good
2023/03/17 16:39:23 INFO:   manifest sha256:e2e16842c9b54d985bf1ef9242a313f36b856181f188de21313820e177002501 looks good
2023/03/17 16:39:29 INFO:     blob     sha256:b2aa39c304c27b96c1fef0c06bee651ac9241d49c4fe34381cab84 …
```

cmd/validate: allow multiple args, cache validation results

---

docs/api-spec.md
internal/api/keppel/manifests.go
internal/api/keppel/manifests_test.go
internal/api/registry/manifests.go
internal/api/registry/manifests_test.go

All usage of these names in our internal applications (Gatekeeper and Elektra) has been removed. Customers likely did not use these names because they existed for a short amount of time only and were not publicly announced.

remove Trivy-specific names

---

cmd/trivyproxy/main.go

The following now gets transformed into one line:
```
ERROR: scan error 6af3a3d97a42b331f5fca50a653bbc4bf1d61846ff00cbceeac17dae1b482b1a: trivy proxy did not return 200: 500 trivy: exit status 1:
INFO    Vulnerability scanning is enabled
FATAL   image scan error: scan error: unable to initialize a scanner: unable to initialize the remote docker scanner: 4 errors occurred:
* unable to inspect the image (keppel.eu-de-1.cloud.sap/someone/something/something@sha256:4719d476278718e84c148d5845d856781afaa17514daf851d894739bad76e660): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
* Get "https://keppel.eu-de-1.cloud.sap/v2/": dial tcp 10.0.0.0:443: connect: connection refused
```
```
trivy: ABC: ERROR: scan error …
```

trivyproxy: transform trivy log lines into a single line

---

internal/tasks/manifests.go

Since we moved them into one line, this is no longer necessary

Don't log trivy errors as uuid

---

internal/drivers/openstack/swift.go

Counterproposal for #278, see comments there.

swift: do not treat 404 as an error during AbortBlobUpload

---

internal/api/keppel/accounts.go

Before this we could get diffs like the following:
```diff
],
"rbac_policies": [
{
+        "match_cidr": "1.2.3.4/32",
"match_repository": ".*",
"permissions": [
-          "anonymous_pull"
+          "anonymous_first_pull"
]
},
{
-        "match_cidr": "1.2.3.4/32",
"match_repository": ".*",
"permissions": [
-          "anonymous_first_pull"
+          "anonymous_pull"
]
}
],
```

Sort /keppel/v1/accounts/:account api endpoint also by match_cidr

---

internal/api/keppel/accounts.go
internal/api/keppel/accounts_test.go
internal/keppel/database.go
internal/keppel/gc_policy.go
internal/keppel/models.go
internal/keppel/rbac_policy.go

There is not really any advantage to having the RBAC policies in their own table, so I want to move them into the accounts table in order to simplify the code that writes policies into the DB, similar to what we already have for GC policies and security scan policies.
This first phase just adds the new field and makes the Keppel API populate it whenever it touches the rbac_policies table. Once we have this rolled out and the new field is filled on all accounts, we will move into the next phase where the old table is removed and all usages are cut over to the new table.

add new accounts.rbac_policies_json field

---

cmd/api/gui_redirect.go
internal/api/auth/api_test.go
internal/api/keppel/accounts.go
internal/api/keppel/accounts_test.go
internal/api/keppel/api_test.go
internal/api/keppel/audit.go
internal/api/peer/api_test.go
internal/api/registry/blobs_test.go
internal/api/registry/manifests_test.go
internal/api/registry/replication_test.go
internal/auth/filter.go
internal/keppel/database.go
internal/keppel/models.go
internal/keppel/rbac_policy.go

This simplifies a lot of the CRUD for accounts and RBAC policies, and reduces the number of SQL queries for each auth by one, at the expense of making `accounts` records a bit larger.
I have verified that the logic from the previous PR has migrated all existing policies into the new DB column, so it is safe to drop the old table.

replace `rbac_policies` table with `accounts.rbac_policies_json`

---

internal/api/keppel/accounts.go
internal/api/keppel/accounts_test.go
internal/keppel/rbac_policy.go
internal/keppel/replication.go
internal/models/platform_filter.go
internal/processor/accounts.go

- load `originalAccount` very early to remove the distinction between early and late validations
- move more validation code to live in the respective types (esp. ReplicationPolicy and RBACPolicy)
- have less code in the update phase for existing accounts

refactor handlePutAccount

---

internal/keppel/database.go

```
Before:
> EXPLAIN ANALYZE UPDATE blob_mounts SET can_be_deleted_at = NOW() WHERE repo_id = 1234 AND can_be_deleted_at IS NULL AND blob_id NOT IN (SELECT DISTINCT blob_id FROM manifest_blob_refs WHERE repo_id = 1234);
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                                                       |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Update on blob_mounts  (cost=339.62..8881.41 rows=0 width=0) (actual …
```

Add index to some queries in BlobMountSweepJob

---

internal/trivy/trivy.go

As it turns out, `stypes.DetectedVulnerability` is missing some fields that exist in the wild, specifically the `PkgIdentifier` field (which is different from `PkgID`).

relax the strictness requirement for unmarshalling Trivy reports

---

docs/drivers/auth-keystone.md
go.mod
go.sum
internal/api/keppel/accounts.go
internal/api/keppel/api.go
internal/api/keppel/audit.go
internal/api/keppel/liquid.go
internal/api/keppel/quotas.go
internal/api/keppel/quotas_test.go
internal/processor/audit.go
internal/processor/quotas.go
vendor/github.com/sapcc/go-api-declarations/liquid/availability_zone.go
vendor/github.com/sapcc/go-api-declarations/liquid/doc.go
vendor/github.com/sapcc/go-api-declarations/liquid/info.go
vendor/github.com/sapcc/go-api-declarations/liquid/metrics.go
vendor/github.com/sapcc/go-api-declarations/liquid/overcommit_factor.go
vendor/github.com/sapcc/go-api-declarations/liquid/quota.go
vendor/github.com/sapcc/go-api-declarations/liquid/report_capacity.go
vendor/github.com/sapcc/go-api-declarations/liquid/report_usage.go
vendor/github.com/sapcc/go-api-declarations/liquid/subdivisions.go
vendor/github.com/sapcc/go-api-declarations/liquid/unit.go
vendor/modules.txt

There is already a quota/usage API implementation in `internal/api/keppel/` that does roughly the same thing, so this mostly just translates to and from the payload types used by LIQUID. The diff ended up being a bit bigger because I moved some stuff around to avoid code duplication.

add LIQUID support

---

internal/auth/token.go

We are seeing problems where Trivy rejects our tokens as "not valid yet", so there appears to be some clock drift going on. This might help alleviate the situation.

issue tokens with nbf 1 second in the past

---

cmd/api/main.go

The guiRedirecter thing matches basically everything and thus needs to come last.

fix HTTP route to pprofapi

---

internal/api/keppel/accounts_test.go
internal/api/keppel/manifests.go
internal/api/keppel/manifests_test.go
internal/api/registry/api.go
internal/api/registry/uploads.go
internal/api/utils.go
internal/drivers/basic/ratelimit.go
internal/drivers/filesystem/storage.go
internal/drivers/openstack/swift.go
internal/drivers/trivial/storage.go
internal/keppel/account.go
internal/keppel/database_helpers.go
internal/keppel/ratelimit_driver.go
internal/keppel/storage_driver.go
internal/keppel/validation.go
internal/models/account.go
internal/processor/accounts.go
internal/processor/blobs.go
internal/processor/manifests.go
internal/processor/processor.go
internal/tasks/account_management.go
internal/tasks/blobs.go
internal/tasks/image_gc.go
internal/tasks/manifests.go
internal/tasks/manifests_test.go
internal/tasks/storage.go
internal/tasks/storage_test.go
internal/tasks/uploads.go
internal/tasks/uploads_test.go
internal/test/helper_validate.go

The StorageDriver and most Processor methods are changed to only take the models.ReducedAccount instead of the full models.Account type.
This allows the Registry API (which is the most-used one by a wide margin) to only load ReducedAccount. This should reduce the read load on the DB noticeably.

add models.ReducedAccount

---

internal/api/keppel/liquid.go

This is a new capability added in go-api-declarations 1.13.0 which will eventually become mandatory in Limes.

api/liquid: add topology declaration

---

internal/api/keppel/accounts.go
internal/api/keppel/accounts_test.go
internal/keppel/account.go
internal/keppel/database.go
internal/models/account.go
internal/processor/accounts.go

In order to not break the account deletion workflow in the Elektra UI.

bring back accounts.in_maintenance temporarily

---

cmd/api/main.go
cmd/janitor/main.go
docs/operator-guide.md
internal/api/keppel/api.go
internal/api/registry/api.go
internal/keppel/auditor.go
internal/processor/processor.go
internal/tasks/janitor.go
internal/test/mock_auditor.go
internal/test/setup.go

This is the most straight-forward port of the bunch because the audittools.Auditor interface is upstreamed from Keppel.

use new go-bits/audittools API

---

internal/client/validate.go
internal/drivers/trivial/account_management.go
internal/drivers/trivial/auth.go
internal/drivers/trivial/federation.go
internal/drivers/trivial/inbound_cache.go
internal/test/content.go

```
$ golangci-lint run --fix
internal/drivers/trivial/inbound_cache.go:38:58: string `trivial` has 5 occurrences, make it a constant (goconst)
internal/client/validate.go:107:2: importShadow: shadow of imported from 'github.com/opencontainers/go-digest' package 'digest' (gocritic)
internal/test/content.go:353:2: importShadow: shadow of imported from 'github.com/containers/image/v5/manifest' package 'manifest' (gocritic)
```

fix new lints as of golangci-lint 2.1.2

---

internal/drivers/basic/account_management.go
internal/keppel/account.go

We forgot about this in #538. The config file for managed accounts uses a slightly different format from what the API uses, and thus has to use a different type declaration that needs to be updated separately. I made a note to ensure we don't forget this when changing the API in the future.

support "tag_policies" field in managed accounts

---

internal/api/keppel/fixtures/trivy-report-spdx.json
internal/api/keppel/manifests.go
internal/api/keppel/manifests_test.go

Also, refuse to compute expensive reports in the API process. Only the janitor process should do that (as added in #539), because it has a bigger RAM allocation and the computation does not slow down other API requests.
I also took the opportunity to pull the tests for the trivy_report endpoint out of the big hairball that is TestManifestsAPI().

serve cached Trivy reports from API

---

cmd/trivyproxy/main.go

@SuperSandro2000 pointed out that this flag exists, so we should probably use it to avoid unexpected dataflows out of the datacenter:
```
$ trivy version | head -n1
Version: 0.63.0
$  trivy image --help | grep telemetry
--disable-telemetry           disable sending anonymous usage data to Aqua
```

cmd/trivyproxy: disable Trivy telemetry

---

internal/keppel/database.go

This migration does not work as-is. In real deployments, we have plenty of images in "Rotten" that have `next_check_at` because that field is NOT NULL before this migration, so the CHECK constraint will fail on these columns.
In order to allow the constraint to be added, we need to change those to a different vuln_status. "Pending" is a sensible choice.
The alternative of setting `next_check_at = NULL` is not feasible. We _want_ to re-run vulnerability checking on all rotten images exactly once to generate the synthetic report that #579 defines.

fix DB migration
